### ISSUE TITLE
Fix blank window when FTDI drivers don't load

### ISSUE THREAD

**Issue by qwertychouskie** [unofficial-rev-port/REVHubInterface#1]
Bug in original Windows version.

**Comment by Iris-TheRainbow** [comment]
I believe this is intended. The window is blank until a hub is connected. If this is something we dont want, ill look into forcing them to load without a hub connected

**Comment by qwertychouskie** [comment]
I mean the extra window, seen here:
![image](https://github.com/unofficial-rev-port/REVHubInterface/assets/13989090/8da6f480-2902-4eff-9841-5713331f01ba)

**Comment by Iris-TheRainbow** [comment]
oh. Can you double check with the python3 version?

**Comment by qwertychouskie** [comment]
FWIW, I haven't seen this issue pop up, perhaps it got eliminated with the Python 3 port.  Closing for now, we can reopen if the issue crops up again.
