### ISSUE TITLE
Servos not holding position sometimes?

### ISSUE THREAD

**Issue by j5155** [unofficial-rev-port/REVHubInterface#13]
https://discord.com/channels/1237587540014403614/1237587540844740733/1237983326955110492
experienced by Oreov using windows 11

**Comment by j5155** [comment]
app shows as disconnected
https://discord.com/channels/1237587540014403614/1237587540844740733/1237985974559178797

**Comment by qwertychouskie** [comment]
Fixed via https://github.com/unofficial-rev-port/REVHubInterface/commit/60e90e62bf2e9016c71247fa5b632dab81463b80
