### ISSUE TITLE
Slowdowns on Windows Pyinstaller

### ISSUE THREAD

**Issue by j5155** [unofficial-rev-port/REVHubInterface#14]
Tested by oreov https://discord.com/channels/1237587540014403614/1237587540844740733/1237975705673924649
Using Windows 11, ONLY experienced with OUR pyinstaller binary (NOT revs, NOT installed with python/pip)

**Comment by j5155** [comment]
shows as disconnected https://discord.com/channels/1237587540014403614/1237587540844740733/1237985974559178797

**Comment by qwertychouskie** [comment]
Are the slowdowns still an issue with the release of 1.3.2?

**Comment by j5155** [comment]
seems like no
