### ISSUE TITLE
Hub light doesn't go green on windows 11

### ISSUE THREAD

**Issue by j5155** [unofficial-rev-port/REVHubInterface#15]
https://discord.com/channels/1237587540014403614/1237587540844740733/1237984217925947443

**Comment by j5155** [comment]
SHOWS DISCONNECTED?? https://discord.com/channels/1237587540014403614/1237587540844740733/1237985974559178797

**Comment by qwertychouskie** [comment]
Fixed via https://github.com/unofficial-rev-port/REVHubInterface/commit/60e90e62bf2e9016c71247fa5b632dab81463b80
