### ISSUE TITLE
Bundle/compile `sflash` for Linux and macOS

### ISSUE THREAD

**Issue by qwertychouskie** [unofficial-rev-port/REVHubInterface#6]
https://github.com/fras/tm4c1294-hw-demo/tree/main/Software/TivaWare/SW-TM4C-2.2.0.295/tools/sflash

Ti probably has some precompiled versions in some random download on their website, but compiling this ourselves is probably easy enough TBH.

**Comment by Iris-TheRainbow** [comment]
Gonna close this as not planned because we don't really have a plan to add this. It can be reopened later if we change our minds.
